[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_dex = "2JubASqT22dDF7uPzZGtwqerKf6f8FhCms694yssT1ay"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/app/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
