[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter = "F5dqGKbj7K9TZybzNKFhViMySM6vsED5f1oAy5rmKcj3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/app/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

